services:
  frontend:
    build: ./ui
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    build: ./api
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network


  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - DATABASE_HOST=127.0.0.1
    ports:
      - 5432:5432
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  frontend_network:
    driver: bridge

  backend_network:
    driver: bridge

volumes:
  postgres_data: